### ISSUE TITLE
 FlowVar[T] (as opposed to Future[T]) prevents the use of a callbacks or timeout

### ISSUE THREAD

**Issue by Clonkk** [status-im/nim-taskpools#10]
I was surprised to find spawn returns a FlowVar when the RFC it's based on speficy a Future must be returned.

With future, it is possible to callback or timeout, AFAIK FlowVar don't have the same API; i.e; doing : 
```nim
let fut = tp.spawn myTask()
fut.addCallback proc() =
  notify.end()
# or
let res = fut. withTimeout(5000).waitFor()
if res:
  notify.success()
else:
  notify.failure()
```

**Comment by mratsim** [comment]
The spec says 

> Future handle
>
> spawn should return a future handle under the type FlowVar[T] or void.
> T is the type returned by the procedure being forked. If it returns void, spawn returns void.
> 
> If the future of a void procedure is needed, the end user SHOULD wrap that function in a function with a return value, for example a function that returns bool or refactor their code.

https://github.com/nim-lang/RFCs/issues/347#awaiting-a-future-required

A future is just a term that means "a handle to the result of an asynchronous computation".

I can't reuse nim's asyncfutures for 2 reasons:
1. They are not threadsafe, they at the very least need `finished` to be an `Atomic[bool]`
2. This library must be compatible with Chronos and so can't rely on asyncdispatch provided functionality.

A proper (practical) solution going forward would be to create an `Awaitable` concept with an API that would be agnostic to the executor.

As mentioned in the spec (at the bottom) and this library, interaction with async/await frameworks are out of scope for now.

## Unifying threads and async

The proposal should go through a spec.

There are 2 approaches that are possible.

### "Gluing" at a higher-level

The first one is "gluing". We embrace the fact that each libraries with a scheduler (async or multithreading) will have its own awaitable type that behave like a future.

We create an Awaitable concept and instead of relying on the concrete `Future[T]` from asyncdispatch, procedures target that concept.

Note that it is not possible to interrupt threads without their cooperation so `withTimeout` cannot be supported. It's actually the same for async runtime: under-the-hood an async runtime has many "cooperation" points, the async/await calls that give control back to the async scheduler and at those points it can choose not to resume. This is not the case for multithreading runtimes, for example if they call a C library. Cooperative cancellation for multithreading runtimes would require the function to have a `cancellationToken: Atomic[bool]` param (or `Channel[bool]`) that is checked at places where it's suitable to exit.

See also Rust woes with regards to cancellation:
- https://gist.github.com/Matthias247/ffc0f189742abf6aa41a226fe07398a8
- https://gist.github.com/Matthias247/354941ebcc4d2270d07ff0c6bf066c64

Besides, unifying an Awaitable concept that works for async and multithreading is non-trivial (C++ has been ddealing with this for decades, http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p0443r14.html).

### Reconciliation at a fundamental level

At a fundamental level, tasks in multithreading runtimes and asynchronous runtimes are built on the notion of "resumable functions".

> A traditional function has 2 capabilities regarding control-flow:
> 
> - On function call, suspend the caller, jump into the function body and run it.
> - On reaching "return", terminate the callee, resume the caller.
> 
> Resumable functions adds the following 2 key capabilities:
> 
> - The callee can suspend itself, returning control to their last resumer.
> - The current owner (not always the initial caller) of the function can suspend itself and resume the continuation.

If control flow in Nim is built on the notion of resumable functions, async and multithreading become compatible.
This is not the only benefit, stream processing is also a kind of resumable function as are infinite lazy lists like in Haskell. Oh, and iterators are also resumable functions (well async is built on closure iterators).

See implementation proposal:
- https://github.com/weavers-guild/weave-io/tree/master/implementation
And design overview, including an Awaitable concept:
- https://github.com/weavers-guild/weave-io/blob/master/design/design_2_continuations.md

Note that this is over a year old and the CPS team might have found alternatives:
- https://github.com/nim-works/cps/tree/master/docs

## Conclusion

Closing because out-of-scope
